# Generated by Django 5.2.1 on 2025-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_remove_article_category_article_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='isHome',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
