# Generated by Django 5.2.1 on 2025-05-18 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
