# Generated by Django 5.2.1 on 2025-05-19 21:59

import articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_author_alter_article_options_remove_article_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.FileField(null=True, upload_to=articles.models.article_file_upload_to, validators=[articles.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
