# Generated by Django 5.2.1 on 2025-05-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_remove_article_authors_article_author_article_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
